github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/nhentai-downloader",
  "https://serp.co/products/nhentai-downloader/reviews/",
  "https://extensions.serp.co/nhentai-downloader",
  "https://browserextensions.io/nhentai-downloader"
]
